package persistence.sql.ddl;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.domain.Person;

class CreateQueryTest {

    @Test
    @DisplayName("Person Entity를 이용한 CREATE QUERY가 정확히 생성 되었는지 검증")
    void create() {
        //given
        final String expectedSql = "CREATE TABLE users ("
            + "id BIGINT generated by default as identity"
            + ", nick_name VARCHAR(255), old INTEGER"
            + ", email VARCHAR(255) not null"
            + ", PRIMARY KEY (id)"
            + ")";

        //when
        final String result = CreateQuery.create(Person.class);

        //then
        assertThat(result).isEqualTo(expectedSql);
    }
}