package persistence.sql.ddl;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.domain.Person;
import persistence.sql.ddl.h2.builder.CreateQueryBuilder;

import static org.assertj.core.api.Assertions.assertThat;

class CreateQueryBuilderTest {

    @Test
    @DisplayName("@Entity 클래스의 create 쿼리 만들기")
    void makeCreateQuery() {
        CreateQueryBuilder createQueryBuilder = new CreateQueryBuilder(Person.class);

        String query = createQueryBuilder.generateCreate();

        assertThat(query).isEqualTo("""
                create table users
                (
                    id bigint NOT NULL generated by default as identity,
                    nick_name varchar(255) NULL,
                    old int NULL,
                    email varchar(255) NOT NULL,
                    primary key (id)
                );
                """);
    }

    @Test
    @DisplayName("@Entity 클래스의 drop 쿼리 만들기")
    void makeDropQuery() {
        CreateQueryBuilder createQueryBuilder = new CreateQueryBuilder(Person.class);

        String query = createQueryBuilder.generateDrop();

        assertThat(query).isEqualTo("drop table users;");
    }
}