package persistence.sql.ddl;

import entity.Person;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@Nested
@DisplayName("CreateDDLQueryBuilder 클래스의")
public class CreateDDLQueryBuilderTest {
    @Nested
    @DisplayName("of 메소드는")
    class of {
        @Nested
        @DisplayName("유효한 엔티티 정보가 주어지면")
        class withValidEntity {
            @Test
            @DisplayName("CREATE DDL을 리턴한다.")
            void testOf() {
                String ddl = CreateDDLQueryBuilder.of(Person.class);
                assertThat(ddl).isEqualTo("CREATE TABLE users ( id BIGINT GENERATED BY DEFAULT AS IDENTITY," +
                        " nick_name VARCHAR(255), old INTEGER NOT NULL, email VARCHAR(255) NOT NULL );");
            }
        }
    }
}
