package persistence.sql.ddl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.sql.fixture.Person;
import persistence.sql.dialect.H2Dialect;
import persistence.sql.fixture.PersonWithAnnotations;
import persistence.sql.fixture.PersonWithTransientAnnotation;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class DdlQueryBuilderTest {
    DdlQueryBuilder queryBuilder;

    @BeforeEach
    void setUp() {
        queryBuilder = new DdlQueryBuilder(new H2Dialect());
    }

    @Test()
    @DisplayName("기본 @Id 어노테이션만 지닌 Person 엔티티의 CREATE TABLE 쿼리를 생성한다.")
    void createPersonDdlTest() {
        String expectedQuery = "CREATE TABLE \"Person\" (" +
                "\"id\" bigint NOT NULL, " +
                "\"name\" varchar(255) NULL, " +
                "\"age\" int NULL, " +
                "PRIMARY KEY (\"id\"));";
        String resultQuery = queryBuilder.getCreateTableQuery(Person.class);

        assertEquals(expectedQuery, resultQuery);
    }

    @Test()
    @DisplayName("GeneratedValue와 Column 어노테이션을 지닌 Person 엔티티의 CREATE TABLE 쿼리를 생성한다.")
    void createPersonWithAnnotationsDdlTest() {
        String expectedQuery = "CREATE TABLE \"PersonWithAnnotations\" (" +
                "\"id\" bigint generated by default as IDENTITY, " +
                "\"nick_name\" varchar(255) NULL, " +
                "\"old\" int NULL, " +
                "\"email\" varchar(255) NOT NULL, " +
                "PRIMARY KEY (\"id\"));";
        String resultQuery = queryBuilder.getCreateTableQuery(PersonWithAnnotations.class);

        assertEquals(expectedQuery, resultQuery);
    }

    @Test()
    @DisplayName("@Table과 @Transient 어노테이션도 지닌 Person 엔티티의 CREATE TABLE 쿼리를 생성한다.")
    void createPersonWithTransientAnnotationDdlTest() {
        String expectedQuery = "CREATE TABLE \"users\" (" +
                "\"id\" bigint generated by default as IDENTITY, " +
                "\"nick_name\" varchar(255) NULL, " +
                "\"old\" int NULL, " +
                "\"email\" varchar(100) NOT NULL, " +
                "PRIMARY KEY (\"id\"));";
        String resultQuery = queryBuilder.getCreateTableQuery(PersonWithTransientAnnotation.class);

        assertEquals(expectedQuery, resultQuery);
    }

    @Test()
    @DisplayName("DROP TABLE 쿼리를 생성한다.")
    void dropDdlTest() {
        String expectedQuery = "DROP TABLE IF EXISTS \"users\"";
        String resultQuery = queryBuilder.getDropTableQuery(PersonWithTransientAnnotation.class);

        assertEquals(expectedQuery, resultQuery);
    }
}
