package persistence.sql.ddl;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class H2CreateDDLGeneratorTest {
    @Test
    void DDL을_생성한다() {
        EntityFields entityFields = EntityFields.of(Person.class);
        H2CreateDDLGenerator h2Creator = new H2CreateDDLGenerator();

        String ddl = h2Creator.generate(entityFields);

        assertThat(ddl).isEqualTo("CREATE TABLE users (id BIGINT generated by default as identity, nick_name VARCHAR(255) , old INTEGER , email VARCHAR(255) not null);");
    }
}
