package persistence.sql.ddl;

import org.junit.jupiter.api.Test;
import persistence.sql.ddl.entity.LengthEntity;
import persistence.sql.ddl.entity.NotSupportStratgyEntity;
import persistence.sql.ddl.exception.NotSupportException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

class H2CreateDDLGeneratorTest {
    @Test
    void DDL을_생성한다() {
        EntityFields entityFields = EntityFields.of(Person.class);
        H2CreateDDLGenerator h2Creator = new H2CreateDDLGenerator();

        String ddl = h2Creator.generate(entityFields);

        assertThat(ddl).isEqualTo("CREATE TABLE users (id BIGINT generated by default as identity, nick_name VARCHAR(255) , old INTEGER , email VARCHAR(255) not null);");
    }

    @Test
    void 컬럼의_길이가_지정된_DDL을_생성한다() {
        EntityFields entityFields = EntityFields.of(LengthEntity.class);
        H2CreateDDLGenerator h2Creator = new H2CreateDDLGenerator();

        String ddl = h2Creator.generate(entityFields);

        assertThat(ddl).isEqualTo("CREATE TABLE LengthEntity (id BIGINT generated by default as identity, address VARCHAR(10) );");
    }

    @Test
    void 제공되지_않는_전략을_사용시_실패한다() {
        EntityFields entityFields = EntityFields.of(NotSupportStratgyEntity.class);
        H2CreateDDLGenerator h2Creator = new H2CreateDDLGenerator();

        assertThatExceptionOfType(NotSupportException.class)
                .isThrownBy(() -> h2Creator.generate(entityFields));
    }
}
