package persistence.sql.meta;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.dialect.h2.H2Dialect;
import persistence.meta.MetaData;
import persistence.sql.fixture.PersonFixture2;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

@DisplayName("1.2 MetaData를 Clazz에서 추출합니다.")
public class MetaDataTest {
  private static Class<PersonFixture2> person;
  private static H2Dialect h2Dialect;

  @BeforeAll
  static void setup() {
    person = PersonFixture2.class;
    h2Dialect = new H2Dialect();
  }

  @Test
  @DisplayName("1.2.1 Clazz가 주어졌을때, H2 Dialect에 맞게 Columns를 만들 수 있다.")
  public void createH2TableFromEntity() {
    MetaData metaData = MetaData.of(person, h2Dialect);

    String createClause = metaData.getCreateClause();

    assertAll(
            () -> assertThat(createClause).isEqualTo("PERSONFIXTURE2 (id BIGINT generated by default as identity PRIMARY KEY,nick_name CHARACTER VARYING ,old INTEGER ,email CHARACTER VARYING NOT NULL,index INTEGER )")
    );
  }
}
