package persistence.sql.ddl.query;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.sql.ddl.Dialect;
import persistence.sql.ddl.H2Dialect;
import persistence.sql.ddl.Person;
import persistence.sql.ddl.fixtures.TestEntityWithAutoIdStrategy;
import persistence.sql.ddl.fixtures.TestEntityWithIdentityIdStrategy;
import persistence.sql.ddl.fixtures.TestEntityWithNullableColumns;
import persistence.sql.ddl.fixtures.TestEntityWithTransientColumn;

import static org.assertj.core.api.Assertions.assertThat;

public class CreateQueryBuilderTest {
    private final Dialect dialect = new H2Dialect();

    @Test
    @DisplayName("Should create a CREATE TABLE query")
    public void shouldCreateCreateTableQuery() {
        CreateQueryBuilder queryBuilder = new CreateQueryBuilder(dialect);
        String query = queryBuilder.build(Person.class);

        assertThat(query).isEqualTo(
                "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY, nick_name VARCHAR(255), old INTEGER, email VARCHAR(255) NOT NULL, PRIMARY KEY (id));"
        );
    }

    @Test
    @DisplayName("Should create create table query for TestEntityWithAutoIdStrategy")
    public void shouldCreateCreateTableQueryForEntityWithAutoIdStrategy() {
        CreateQueryBuilder queryBuilder = new CreateQueryBuilder(dialect);
        String query = queryBuilder.build(TestEntityWithAutoIdStrategy.class);

        assertThat(query).isEqualTo(
                "CREATE TABLE TestEntityWithAutoIdStrategy (id BIGINT , PRIMARY KEY (id));");
    }

    @Test
    @DisplayName("Should create a CREATE TABLE query for TestEntityWithIdentityIdStrategy")
    public void shouldCreateCreateTableQueryForEntityWithIdentityIdStrategy() {
        CreateQueryBuilder queryBuilder = new CreateQueryBuilder(dialect);
        String query = queryBuilder.build(TestEntityWithIdentityIdStrategy.class);

        assertThat(query).isEqualTo(
                "CREATE TABLE TestEntityWithIdentityIdStrategy (id BIGINT GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY (id));"
        );
    }

    @Test
    @DisplayName("Should create a CREATE TABLE query for TestEntityWithNullableColumns")
    public void shouldCreateCreateTableQueryForNullableTestEntity() {
        CreateQueryBuilder queryBuilder = new CreateQueryBuilder(dialect);
        String query = queryBuilder.build(TestEntityWithNullableColumns.class);

        assertThat(query).isEqualTo(
                "CREATE TABLE TestEntityWithNullableColumns (id BIGINT GENERATED BY DEFAULT AS IDENTITY, nullableColumn1 VARCHAR(255), nullableColumn2 VARCHAR(255), nonNullableColumn VARCHAR(255) NOT NULL, PRIMARY KEY (id));"
        );
    }

    @Test
    @DisplayName("Should create a CREATE TABLE query for TestEntityWithTransientColumn")
    public void shouldCreateCreateTableQueryForTransientTestEntity() {
        CreateQueryBuilder queryBuilder = new CreateQueryBuilder(dialect);

        // When
        String query = queryBuilder.build(TestEntityWithTransientColumn.class);

        // Then
        assertThat(query).isEqualTo(
                "CREATE TABLE TestEntityWithTransientColumn (id BIGINT GENERATED BY DEFAULT AS IDENTITY, normalColumn VARCHAR(255), PRIMARY KEY (id));"
        );
    }
}
