package persistence.sql.dml.domain;

import java.util.List;
import java.util.stream.Collectors;

public class Values {

    private static final String COMMA = ", ";

    private final List<Value> values;

    public Values(List<Value> values) {
        this.values = values;
    }

    public String getInsertValues() {
        return values.stream()
                .filter(value -> value.getColumn().isNotTransient())
                .filter(value -> value.getColumn().isNotIdAutoGenerated())
                .map(Value::getValue)
                .collect(Collectors.joining(COMMA));
    }

    public String getWhereValues() {
        return values.stream()
                .map(x -> x.getColumn().getName() + " = " + x.getValue())
                .collect(Collectors.joining(" AND "));
    }
}
