package persistence.dialect;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class DialectTest {
	@DisplayName("각 DB에 맞는 전략을 출력한다.")
	@Test
	void test_getGeneratedStrategy() {
		Assertions.assertAll(
				() -> assertEquals(
						DialectFactory.getDialect("H2").getGeneratedStrategy("IDENTITY"),
						" GENERATED BY DEFAULT AS IDENTITY"),
				() -> assertEquals(
						DialectFactory.getDialect("MySQL").getGeneratedStrategy("IDENTITY"),
						" AUTO_INCREMENT")
		);
	}

	@DisplayName("정의되지 않은 DB에 대한 Dialect를 가져올 경우 Exception이 발생한다.")
	@Test
	void When_IsNotSupportedDB_Then_ThrowException() {
		assertThrows(
				IllegalArgumentException.class,
				() -> DialectFactory.getDialect("Maria")
		);
	}
}