package persistence.sql.ddl.dialect.h2;

import persistence.sql.ddl.dialect.Query;

/**
 * H2 표현식 모음
 */
public interface H2Query extends Query {

    String SPACE = " ";
    String OPEN_PARENTHESIS = "(";
    String CLOSE_PARENTHESIS = ")";
    String COMMA = ",";

    String CREATE_QUERY = "create table";
    String DROP_QUERY = "drop table";

    String IF_EXISTS = "if exists";
    String CASCADE = "CASCADE";
    String NOT_NULL = "not null";

    String PRIMARY_KEY = "primary key";
    String GENERATED_BY = "generated by default as ";

}
