package persistence.meta;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.dialect.h2.H2Dialect;
import persistence.sql.fixture.PersonFixture;
import persistence.sql.fixture.PersonFixture2;

@DisplayName("1.2 MetaDataColumns를 Clazz에서 추출합니다.")
public class MetaDataColumnsTest {
  private static Class<PersonFixture2> personWithoutTransient;
  private static Class<PersonFixture> personWithTransient;
  private static H2Dialect h2Dialect;

  @BeforeAll
  static void setup() {
    personWithoutTransient = PersonFixture2.class;
    personWithTransient = PersonFixture.class;
    h2Dialect = new H2Dialect();
  }

  @Test
  @DisplayName("1.2.1 Column clause를 생성합니다.")
  public void createColumnsDdl() {
    MetaDataColumns dataColumns = MetaDataColumns.of(personWithoutTransient, h2Dialect);

    assertThat(dataColumns.getColumns()).isEqualTo("id BIGINT generated by default as identity PRIMARY KEY,nick_name CHARACTER VARYING ,old INTEGER ,email CHARACTER VARYING NOT NULL,index INTEGER ");
  }

  @Test
  @DisplayName("1.2.3 Transient 애노테이션일 경우 DDL에서 제외한다.")
  public void removeTransientColumns() {
    MetaDataColumns dataColumns = MetaDataColumns.of(personWithTransient, h2Dialect);

    assertThat(dataColumns.getColumns()).isEqualTo("id BIGINT generated by default as identity PRIMARY KEY,nick_name CHARACTER VARYING ,old INTEGER ,email CHARACTER VARYING NOT NULL");
  }
}
