package persistence.sql.ddl.dialect;

import java.lang.reflect.Field;

/**
 * @http://www.h2database.com/html/datatypes.html
 */
public class H2ColumnType implements ColumnType {

    @Override
    public String longType() {
        return "bigint";
    }

    @Override
    public String stringType() {
        return "varchar";
    }

    @Override
    public String intType() {
        return "integer";
    }

    @Override
    public String booleanType() {
        return "boolean";
    }

    @Override
    public String shortType() {
        return "smallint";
    }

    @Override
    public String generationIdentity() {
        return "generated by default as identity";
    }

    @Override
    public String getType(Field field) {
        if (field.getType().equals(String.class)) {
            return this.stringType();
        } else if (field.getType().equals(Long.class)) {
            return this.longType();
        } else if (field.getType().equals(Integer.class)) {
            return this.intType();
        } else {
            throw new RuntimeException("Incompatible field type");
        }
    }
}
