package persistence.sql.ddl.dialect;

import jakarta.persistence.GenerationType;
import persistence.sql.meta.column.Nullable;

import java.sql.Types;

public class H2Dialect extends Dialect {
    @Override
    protected void setDefaultColumnDataTypes() {
        registerColumnDataType(Types.VARCHAR, "varchar(255)");
        registerColumnDataType(Types.INTEGER, "int");
        registerColumnDataType(Types.BIGINT, "bigint");
    }

    @Override
    protected void setDefaultNullableTypes() {
        registerColumnNullableTypes(Nullable.NULL, "NULL");
        registerColumnNullableTypes(Nullable.NOT_NULL, "NOT NULL");
    }

    @Override
    protected void setDefaultPKGenerationTypes() {
        registerPKGenerationTypes(GenerationType.AUTO, "");
        registerPKGenerationTypes(GenerationType.IDENTITY, "generated by default as identity");
    }
}
