package persistence.sql.ddl.dialect;

import jakarta.persistence.GenerationType;
import persistence.sql.ddl.exception.NotSupportException;

import java.sql.Types;

public class H2Dialect implements Dialect {
    @Override
    public String getFieldDefinition(int type) {
        return switch (type) {
            case Types.VARCHAR -> "VARCHAR(%d)";
            case Types.BIGINT -> "BIGINT";
            case Types.INTEGER -> "INTEGER";
            default -> throw new NotSupportException();
        };
    }

    @Override
    public String getGenerationDefinition(GenerationType generationType) {
        return switch (generationType) {
            case IDENTITY -> "generated by default as identity";
            default -> throw new NotSupportException();
        };
    }
}
