package persistence.sql.ddl.query;

import jakarta.persistence.GenerationType;
import persistence.sql.ddl.PrimaryKey;

public class IdentityKeyGenerationStrategy implements PrimaryKeyGenerationStrategy {

    @Override
    public String generatePrimaryKeySQL(PrimaryKey pk) {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public Boolean supports(PrimaryKey pk) {
        return pk.generationType().equals(GenerationType.IDENTITY);
    }
}
