package persistence.sql.ddl.utils;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.sql.ddl.EntityMetaData;
import persistence.sql.ddl.Person;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class ColumnTypeQueryBuilderTest {

    @BeforeEach
    void setUp() {

    }
    @Test
    @DisplayName("컬럼 행별 ddl쿼리를 추출한다.")
    void query() {
        EntityMetaData entityMetaData = new EntityMetaData(Person.class);
        List<String> strings = ColumnQueryBuilder.generateDdlQueryRows(entityMetaData.getColumns());
        assertThat(strings).containsOnly("email VARCHAR(255) not null", "old INTEGER", "nick_name VARCHAR(255)", "id BIGINT generated by default as identity primary key"
        );
    }
}