package persistence.sql.dialect.identity;

public class H2IdentityColumnSupport implements IdentityColumnSupport {
    @Override
    public String getIdentityColumnString() {
        return "generated by default as identity";
    }

    @Override
    public String getIdentityInsertString() {
        return "default";
    }
}
