package persistence.sql.dialect;

import java.util.List;
import java.util.stream.Collectors;

public class H2Dialect implements Dialect {
    private final String quote = "\"";

    public H2Dialect() {
    }

    public String getQuote() {
        return quote;
    }

    @Override
    public String getIdentifierQuoted(String identifier) {
        return quote + identifier + quote;
    }

    @Override
    public String getNullPhrase(Boolean isNull) {
        return isNull ? "NULL" : "NOT NULL";
    }

    @Override
    public String getAutoGeneratedIdentityPhrase() {
        return "generated by default as IDENTITY";
    };

    @Override
    public String getCreateTablePhrase() {
        return "CREATE TABLE";
    }

    @Override
    public String getDropTablePhrase() {
        return "DROP TABLE IF EXISTS";
    }

    @Override
    public String buildPrimaryKeyPhrase(List<String> columnNames) {
        String quotedColumnNames = columnNames.stream()
                .map(this::getIdentifierQuoted)
                .collect(Collectors.joining(", "));

        return String.format("PRIMARY KEY (%s)", quotedColumnNames);
    }

    @Override
    public Boolean shouldSpecifyNotNullOnIdentity() {
        return false;
    };
}
