package persistence.sql.ddl.dialect.h2;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import persistence.entity.Person_Week1_Step2_Demand1;
import persistence.entity.Person_Week1_Step2_Demand2;
import persistence.entity.Person_Week1_Step2_Demand3;
import persistence.sql.ddl.entity.EntityData;

import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

class H2CreateQueryTest {

    @DisplayName("엔티티에 알맞는 H2 create 쿼리를 생성한다.")
    @ParameterizedTest
    @MethodSource("createQueryTestParam")
    void createQueryTest(Class<?> entityClass, String expectedQuery) {
        H2CreateQuery createQuery = new H2CreateQuery();
        String actualQuery = createQuery.generateQuery(new EntityData(entityClass));
        assertThat(actualQuery).isEqualTo(expectedQuery);
    }

    private static Stream<Arguments> createQueryTestParam() {
        return Stream.of(
                Arguments.of(Person_Week1_Step2_Demand1.class, "create table person_week1_step2_demand1 (id bigint not null, name varchar(255), age integer, primary key (id))"),
                Arguments.of(Person_Week1_Step2_Demand2.class, "create table person_week1_step2_demand2 (id bigint generated by default as identity, nick_name varchar(255), old integer, email varchar(255) not null, primary key (id))"),
                Arguments.of(Person_Week1_Step2_Demand3.class, "create table users (id bigint generated by default as identity, nick_name varchar(255), old integer, email varchar(255) not null, primary key (id))")
        );
    }

}