package persistence.sql.dialect.identity;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class H2IdentityColumnSupportTest {

    private final IdentityColumnSupport identityColumnSupport = new H2IdentityColumnSupport();

    @DisplayName("H2 DB 의 자동 생성 예약어를 반환한다")
    @Test
    public void createToH2IdentityColumnString() throws Exception {
        // when
        final String identityColumnString = identityColumnSupport.getIdentityColumnString();

        // then
        assertThat(identityColumnString).isEqualTo("generated by default as identity");
    }

}
