package persistence;

public class Id implements Node {
    private static final String KEYWORD = "%s bigint generated by default as identity";
    private final String uniqueKey;

    public Id(String uniqueKey) {
        this.uniqueKey = uniqueKey;
    }

    @Override
    public String expression() {
        return String.format(KEYWORD, uniqueKey);
    }
}
