package persistence.model;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import persistence.model.meta.DataType;
import persistence.model.util.ReflectionUtil;
import persistence.sql.dialect.Dialect;

import java.lang.reflect.Field;
import java.util.Optional;

public class EntityColumn {
    private final String name;

    private final DataType dataType;

    private final int length;

    public final Boolean isPrimary;

    public final Boolean isNullable;

    public final Boolean isAutoGeneratedIdentity;

    public EntityColumn(
            String name,
            DataType dataType,
            int length,
            Boolean isPrimary,
            Boolean isNullable,
            Boolean isAutoGeneratedIdentity
    ) {
        this.name = name;
        this.dataType = dataType;
        this.length = length;
        this.isPrimary = isPrimary;
        this.isNullable = isNullable;
        this.isAutoGeneratedIdentity = isAutoGeneratedIdentity;
    }

    public static EntityColumn build(Field field, Dialect dialect) {
        String name = getName(field);
        int length = getLength(field);
        DataType dataType = dialect.getDataType(field.getType());

        return new EntityColumn(
                name, dataType, length, isPrimary(field), isNullable(field), isAutoGeneratedIdentity(field)
        );
    }

    private static String getName(Field field) {
        return ReflectionUtil.getAnnotationIfPresent(field, Column.class)
                .map(Column::name)
                .filter(name -> !name.isEmpty())
                .orElse(field.getName());
    }

    private static int getLength(Field field) {
        final int COLUMN_DEFAULT_LENGTH = 255;
        Optional<Column> annotation = ReflectionUtil.getAnnotationIfPresent(field, Column.class);

        if (annotation.isPresent() && annotation.get().length() != COLUMN_DEFAULT_LENGTH) {
            return annotation.get().length();
        }
        return COLUMN_DEFAULT_LENGTH;
    }


    private static Boolean isNullable(Field field) {
        if (field.isAnnotationPresent(Id.class)) {
            return false;
        }
        if (!field.isAnnotationPresent(Column.class)) {
            return true;
        }
        return ReflectionUtil.getAnnotationIfPresent(field, Column.class)
                .map(column -> column.nullable() && !column.unique())
                .orElse(false);
    }

    private static Boolean isPrimary(Field field) {
        return field.isAnnotationPresent(Id.class);
    }

    private static Boolean isAutoGeneratedIdentity(Field field) {
        return ReflectionUtil.getAnnotationIfPresent(field, GeneratedValue.class)
                .map(annotation -> annotation.strategy().equals(GenerationType.IDENTITY))
                .orElse(false);
    }

    public String getName() {
        return name;
    }

    public DataType getDataType() {
        return dataType;
    }

    public int getLength() {
        return length;
    }

    public Boolean isAutoGeneratedIdentity() {
        return isAutoGeneratedIdentity;
    }

    public Boolean isPrimary() {
        return isPrimary;
    }

    public Boolean isNullable() {
        return isNullable;
    }
}
