package persistence.model;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import persistence.model.meta.DataType;
import persistence.model.util.ReflectionUtil;

import java.lang.reflect.Field;

public class EntityColumn {
    private final String name;

    private final Field field;

    private final DataType dataType;

    public EntityColumn(String name, Field field, DataType dataType) {
        this.name = name;
        this.field = field;
        this.dataType = dataType;
    }

    public static EntityColumn build(Field field) {
        String name = getName(field);
        DataType dataType = DataType.getByJavaType(field.getType());
        return new EntityColumn(name, field, dataType);
    }

    private static String getName(Field field) {
        return ReflectionUtil.getAnnotationIfPresent(field, Column.class)
                .map(Column::name)
                .filter(name -> !name.isEmpty())
                .orElse(field.getName());
    }

    public String getName() {
        return name;
    }

    public Field getField() {
        return field;
    }

    public DataType getDataType() {
        return dataType;
    }

    public Boolean isNullable() {
        if (field.isAnnotationPresent(Id.class)) {
            return false;
        }
        if (!field.isAnnotationPresent(Column.class)) {
            return true;
        }
        return ReflectionUtil.getAnnotationIfPresent(field, Column.class)
                .map(column -> column.nullable() && !column.unique())
                .orElse(false);
    }

    public Boolean isPrimary() {
        return field.isAnnotationPresent(Id.class);
    }

    public Boolean isAutoGeneratedIdentity() {
        return ReflectionUtil.getAnnotationIfPresent(field, GeneratedValue.class)
                .map(annotation -> annotation.strategy().equals(GenerationType.IDENTITY))
                .orElse(false);
    }
}
