package persistence.sql.ddl.definition;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import persistence.sql.ddl.fixtures.EntityWithAutoIdStrategy;
import persistence.sql.ddl.fixtures.EntityWithIdentityIdStrategy;

import static org.assertj.core.api.Assertions.assertThat;

public class PrimaryKeyQueryableTest {

    @Test
    @DisplayName("GeneratedValue annotation이 없으면 IDENTITY 전략이 아닌 AUTO 전략으로 생성되어야 한다.")
    public void shouldCreateAutoIdStrategy() throws Exception {
        // Given
        Class<EntityWithAutoIdStrategy> clazz = EntityWithAutoIdStrategy.class;
        PrimaryKey pk = new PrimaryKey(clazz.getDeclaredField("id"));

        // When
        StringBuilder query = new StringBuilder();
        pk.apply(query);

        // Then
        String expectedQuery = "id BIGINT , ";
        assertThat(query.toString()).isEqualTo(expectedQuery);
    }

    @Test
    @DisplayName("GeneratedValue annotation이 IDENTITY 전략으로 지정되면 IDENTITY 전략으로 생성되어야 한다.")
    public void shouldCreateIdentityIdStrategy() throws Exception {
        // Given
        Class<EntityWithIdentityIdStrategy> clazz = EntityWithIdentityIdStrategy.class;
        PrimaryKey pk = new PrimaryKey(clazz.getDeclaredField("id"));

        // When
        StringBuilder query = new StringBuilder();
        pk.apply(query);

        // Then
        System.out.println(query);
        String expectedQuery = "id BIGINT GENERATED BY DEFAULT AS IDENTITY, ";
        assertThat(query.toString()).isEqualTo(expectedQuery);
    }
}
