package persistence.sql.ddl.domain;

import jakarta.persistence.GenerationType;

import java.lang.reflect.Field;

public class Constraint {

    private final boolean isPrimaryKey;
    private final boolean isAutoGenerated;
    private final boolean isNotNull;

    public Constraint(Field field) {
        this.isPrimaryKey = field.isAnnotationPresent(jakarta.persistence.Id.class);
        this.isAutoGenerated = isAutoGenerated(field);
        this.isNotNull = isNotNull(field);
    }

    private boolean isAutoGenerated(Field field) {
        return field.isAnnotationPresent(jakarta.persistence.GeneratedValue.class) && !field.getAnnotation(jakarta.persistence.GeneratedValue.class).strategy().equals(GenerationType.SEQUENCE);
    }

    private boolean isNotNull(Field field) {
        return field.isAnnotationPresent(jakarta.persistence.Column.class) && !field.getAnnotation(jakarta.persistence.Column.class).nullable();
    }

    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public boolean isNotNull() {
        return isNotNull;
    }
}
