package persistence.sql.ddl.domain;

import persistence.sql.ddl.constraint.GeneratedValueH2Constraint;
import persistence.sql.ddl.constraint.H2Constraint;

import java.util.List;
import java.util.stream.Collectors;

public class Constraints {

    private static final String SPACE = " ";

    private final List<H2Constraint> constraints;

    public Constraints(List<H2Constraint> constraints) {
        this.constraints = constraints;
    }

    public String getConstraintsQuery() {
        return constraints.stream()
                .map(H2Constraint::getConstraintQuery)
                .collect(Collectors.joining(SPACE));
    }

    public boolean isIdAutoGenerated() {
        return constraints.stream()
                .filter(GeneratedValueH2Constraint.class::isInstance)
                .map(GeneratedValueH2Constraint.class::cast)
                .anyMatch(GeneratedValueH2Constraint::isIdAutoGenerated);
    }

}
