package persistence.sql.ddl.domain;


import jakarta.persistence.GenerationType;

public class H2DdlKeyGenerator implements DdlKeyGenerator {

    @Override
    public String generator(final GenerationType generationType) {
        if (GenerationType.IDENTITY == generationType) {
            return " generated by default as identity";
        }

        return "";
    }
}
