package persistence;

import org.junit.jupiter.api.Test;

import java.util.DuplicateFormatFlagsException;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ColumnsTest {

    @Test
    void 중복이름_예외발생() {
        assertThrows(DuplicateFormatFlagsException.class, () -> {
            new Columns(List.of(ColumnNode.of("id", Long.class, -1, true), ColumnNode.of("id", Long.class, -1, false)));
        });
    }

    @Test
    void 유니크는_하나만_존재해야함() {
        assertThrows(DuplicateFormatFlagsException.class, () -> {
            new Columns(List.of(ColumnNode.of("id", Long.class, -1, true), ColumnNode.of("name", String.class, 255, true)));
        });
    }

    @Test
    void 컬럼목록출력() {
        Columns columns = new Columns(List.of(ColumnNode.of("id", Long.class, -1, true), ColumnNode.of("name", String.class, 255, false)));

        String query = columns.expression();

        assertThat(query).isEqualTo("id bigint generated by default as identity,name varchar(255) not null,primary key (id)");
    }
}
