package persistence.entity;

import database.DatabaseServer;
import database.H2;
import entity.Person;
import jdbc.JdbcTemplate;
import org.junit.jupiter.api.*;
import persistence.sql.Query;
import persistence.sql.dialect.h2.H2Dialect;

import static org.assertj.core.api.Assertions.assertThat;

class SimpleEntityManagerTest {


    private static DatabaseServer server;
    private static JdbcTemplate jdbcTemplate;
    private static final Query QUERY = new Query(new H2Dialect());

    @BeforeAll
    static void beforeAll() throws Exception {
        try {
            server = new H2();
            server.start();
            jdbcTemplate = new JdbcTemplate(server.getConnection());
        } catch (Exception e) {
            throw new Exception(e);
        }
    }

    @AfterAll
    static void afterAll() {
        server.stop();
    }

    @BeforeEach
    void beforeEach() {
        jdbcTemplate.execute("create table users (id bigint generated by default as identity, nick_name varchar(255), old integer, email varchar(255) not null, primary key (id))");
        jdbcTemplate.execute("insert into users (id, nick_name, old, email) values (default, 'test1', 10, 'test1@gmail.com')");
    }

    @AfterEach
    void afterEach() {
        jdbcTemplate.execute("drop table if exists users CASCADE");
    }

    @DisplayName("EntityManger#find를 통해 Entity를 조회한다.")
    @Test
    void findTest() {
        // given
        EntityManager entityManager = new SimpleEntityManager(QUERY, jdbcTemplate);
        Person expected = new Person(1L, "test1", 10, "test1@gmail.com", 0);

        // when
        Person actual = entityManager.find(Person.class, 1L);

        // then
        assertThat(actual.equals(expected)).isTrue();
    }

    @DisplayName("EntityManger#persist를 통해 Entity를 저장한다.")
    @Test
    void persistTest() {
        // given
        EntityManager entityManager = new SimpleEntityManager(QUERY, jdbcTemplate);
        Person testEntity = new Person(2L, "test2", 11, "test2@gmail.com", 0);

        // when
        entityManager.persist(testEntity);
        Person found = entityManager.find(Person.class, 2L);

        // then
        assertThat(found.equals(testEntity)).isTrue();
    }

}
