package persistence.sql.fixture;

import jakarta.persistence.*;

@Table(name = "users")
@Entity
public class PersonFixture {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "nick_name")
  private String name;

  @Column(name = "old")
  private Integer age;

  @Column(nullable = false)
  private String email;

  @Transient
  private Integer index;

}

            /*
              (id bigint PRIMARY KEY generated by default as identity,
               nick_name varchar,
               old integer,
               email varchar NOT NULL,
               index integer)
             */
