package persistence.sql.metadata;

import java.util.Arrays;

public enum GeneratedType {

    IDENTITY(" GENERATED BY DEFAULT AS IDENTITY");

    private String dbGeneratedTypeName;

    GeneratedType(String dbGeneratedTypeName) {
        this.dbGeneratedTypeName= dbGeneratedTypeName;
    }
    public java.lang.String getDbGeneratedTypeName() {
        return dbGeneratedTypeName;
    }

    public static String convertTypeClassToName(String dbGeneratedTypeName) {
        return Arrays.stream(GeneratedType.values())
                .filter(x -> x.name().equals(dbGeneratedTypeName))
                .map(x -> x.getDbGeneratedTypeName())
                .findAny()
                .orElse("");
    }
}
