package persistence.dialect.H2;

import java.util.Arrays;

public enum H2GeneratedType {

    IDENTITY(" GENERATED BY DEFAULT AS IDENTITY");

    private final String strategy;

    H2GeneratedType(String strategy) {
        this.strategy = strategy;
    }
    public String getStrategy() {
        return strategy;
    }

    public static String getStrategyByTypeName(String typeName) {
        return Arrays.stream(H2GeneratedType.values())
                .filter(x -> x.name().equals(typeName))
                .map(H2GeneratedType::getStrategy)
                .findAny()
                .orElse("");
    }
}
