package persistence.sql.ddl;

public class ConstraintBuilder {
    private final static String PRIMARY_CONSTRAINT = " PRIMARY KEY";
    private final static String NOT_NULL_CONSTRAINT = " NOT NULL";

    public ConstraintBuilder() {
    }

    public String buildPrimaryKey(Constraint constraint) {
        if(constraint.isPrimaryKey()) {
            return PRIMARY_CONSTRAINT;
        }

        return "";
    }

    public String buildNullable(Constraint constraint) {
        if(!constraint.isNullable()) {
            return NOT_NULL_CONSTRAINT;
        }

        return "";
    }

    public String bulidGeneratedType(Constraint constraint) {
        switch (constraint.getGeneratedType()) {
            case "IDENTITY" :
                return " GENERATED BY DEFAULT AS IDENTITY";

            default:
                return "";
        }
    }
}
