package persistence.sql.ddl.constraint;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import java.lang.reflect.Field;

public class PrimaryKey implements Constraint {

    private final GenerationType generationType;

    public PrimaryKey(Field field) {
        this.generationType = createGenerationType(field);
    }

    private GenerationType createGenerationType(Field field) {
        if (field.isAnnotationPresent(GeneratedValue.class)) {
            return field.getAnnotation(GeneratedValue.class).strategy();
        }
        return null;
    }

    public GenerationType getGenerationType() {
        return generationType;
    }

    public boolean isNotAutoGenerated() {
        return generationType == null || generationType.equals(GenerationType.SEQUENCE);
    }

}
