package persistence.model;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;

import static org.junit.jupiter.api.Assertions.*;

public class EntityColumnUnitTest {
    static class TestEntity {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;

        @Column(name = "nick_name", nullable = false)
        private String name;

        @Column(name = "login_id")
        private String email;

        private Integer age;
    }

    private Field idField;

    private Field nameField;

    private Field emailField;

    private Field ageField;

    @BeforeEach
    void setUp() throws NoSuchFieldException {
        idField = TestEntity.class.getDeclaredField("id");
        nameField = TestEntity.class.getDeclaredField("name");
        emailField = TestEntity.class.getDeclaredField("email");
        ageField = TestEntity.class.getDeclaredField("age");
    }

    @Test
    @DisplayName("@Column 어노테이션이 없는 필드는 default null 컬럼이다.")
    void testDefaultNullWithoutColumnAnnotation() {
        assertTrue(EntityColumn.build(ageField).isNullable());
    }

    @Test
    @DisplayName("@Column 어노테이션이 있고 null 키에 대한 값이 없는 필드는 default null 컬럼이다.")
    void testDefaultNullWithColumnAnnotation() {
        assertTrue(EntityColumn.build(emailField).isNullable());
    }

    @Test
    @DisplayName("@Column 어노테이션이 있고 null = false인 필드는 not null이다.")
    void testNotNullWithColumnAnnotation() {
        assertFalse(EntityColumn.build(nameField).isNullable());
    }

    @Test
    @DisplayName("@Id 어노테이션이 있으면 PK이다.")
    void testPrimaryWithIdAnnotation() {
        assertAll(
                () -> assertTrue(EntityColumn.build(idField).isPrimary()),
                () -> assertFalse(EntityColumn.build(nameField).isPrimary()),
                () -> assertFalse(EntityColumn.build(emailField).isPrimary()),
                () -> assertFalse(EntityColumn.build(ageField).isPrimary())
        );
    }

    @Test
    @DisplayName("@GeneratedValue 어노테이션이 있고 GenerationType이 Identity면 값이 자동으로 생성되는 컬럼이다.")
    void testAutoGeneratedIdentityWithGeneratedValueAnnotation() {
        assertAll(
                () -> assertTrue(EntityColumn.build(idField).isAutoGeneratedIdentity()),
                () -> assertFalse(EntityColumn.build(nameField).isAutoGeneratedIdentity()),
                () -> assertFalse(EntityColumn.build(emailField).isAutoGeneratedIdentity()),
                () -> assertFalse(EntityColumn.build(ageField).isAutoGeneratedIdentity())
        );
    }
}
